from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('uMCN', src, depend = ['UMCN_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
