from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('uMCN', src, depend = ['PKG_USING_UMCN'], CPPPATH = CPPPATH)

Return('group')
